### PR TITLE
Loading Animation

### PR DESCRIPTION
**Pull request by KelvinHoky**
The original animation is at 
https://codepen.io/pawelqcm/pen/ObwyNe
The owner use SCSS

### CODE REVIEW

**Comment by MohamedMafaz** [comment]
Can you integrate it with index.html

**Comment by KelvinHoky** [comment]
Sure thing, You mean like a preload for the page right?

**Comment by KelvinHoky** [comment]
Alright ive integrated it feel free to tell me if you need anything else ✌ Have a great day

**Comment by MohamedMafaz** [comment]
Dear @KelvinHoky,

I hope this email finds you well. I am writing to you today because I am working on a new website and I am in need of your help with integrating ChatGPT API. I am hoping that you can help me with the integration process.

The front end work for my website is almost complete and I am now moving on to integrating the API. I have been working on this project for a while now and I really want to make sure that I get it right. I believe that your expertise will be invaluable in helping me achieve this.

If you are willing to help me, I would be happy to share the source code with you. I am available for a chat at your convenience to discuss this further and answer any questions you may have.

Thank you for considering my request. I appreciate your time and expertise.

Best regards,
Mohamed Mafaz P R

**Comment by KelvinHoky** [comment]
Hey, Kelvin here✌.My apologies for the delayed response.Thank you for
considering me for this task. However, I regret to inform you that I won't
be able to integrate ChatGPT at this time. While I am eager to expand my
skills, I am still learning how to work with the platform. Additionally, I
wanted to mention that integrating ChatGPT requires a paid API subscription
which I am unable to afford at the moment.

Thank you again for considering me, and I wish you all the best in finding
a suitable solution. Best regards
Kelvin Hoky

**Comment by MohamedMafaz** [comment]
Thanks for your info. I'll think about any other ways to implement this idea

**Pull request merged**
