### PR TITLE
initial build of contact page

### PR DESCRIPTION
**Pull request by willdelorm**
@MohamedMafaz Here's an initial pass on the Contact page. Let me know what you think!

### CODE REVIEW

**Comment by MohamedMafaz** [comment]
Can you give me the live link of the website. Just host your repo in Github Pages and drop me a link

**Comment by willdelorm** [comment]
https://willdelorm.github.io/contactus.html

**Comment by MohamedMafaz** [comment]
Screenshot (127)
In this contact us page navbar is just overlaped the form. Is there any possibility to fix it

**Comment by willdelorm** [comment]
Hey Mohamed,

I'm not sure why that's happening, it looks fine in my Chrome browser. I've
made an adjustment to how the padding was distributed. Would you take
another look?
https://willdelorm.github.io/contactus.html

If it looks fine, I'll submit another PR.

**Pull request merged**
