### PR TITLE
I fixed your hidden problem of list of navbar while scrolling down

### PR DESCRIPTION
**Pull request by BrightTNut**

### CODE REVIEW

**Comment by MohamedMafaz** [comment]
Can you give me the live hosted website. Just Host it in Gthub pages and drop me a link

**Comment by MohamedMafaz** [comment]
kindly follow background colour and font styles as same as home page

**Comment by BrightTNut** [comment]
okay I will sent you a link

**Comment by BrightTNut** [comment]
https://brighttnut.github.io/Fodome/

**Pull request merged**
