### PR TITLE
Updated some HTML and CSS lines of codes

### PR DESCRIPTION
**Pull request by therealtmmy**

### CODE REVIEW

**Comment by MohamedMafaz** [comment]
Can you give me the live link which is hosted in Github Pages?

**Comment by MohamedMafaz** [comment]
Hey @therealtmmy
I appreciate your spirit for Open source. I have another repo and I am looking for a contributor for this issue. Please take a look at that. You can deploy in any free hoating providing service. https://github.com/MohamedMafaz/Propoplex/issues/11

**Comment by therealtmmy** [comment]
I don't have a live link to it. Please change the live changes I made. Merge it, deploy it to production and access it.

**Comment by MohamedMafaz** [comment]
Okay! I'll merge it. Can you please take this issue. https://github.com/MohamedMafaz/Propoplex/issues/11  I can't able to code further in that project before this issue completed

**Pull request merged**
