### PR TITLE
Jackwebdev-reponsiveness

### PR DESCRIPTION
**Pull request by Jack-WebDev**
I have made the home page responsive, including the new changes you added.

If you have any concerns and you want me to make new changes or undo some changes, do let me know.

### CODE REVIEW

**Comment by MohamedMafaz** [comment]
Can you provide a live link which is hosted in Github pages or Vercel?

**Comment by Jack-WebDev** [comment]
https://jack-webdev.github.io/Fodome/

**Comment by Jack-WebDev** [comment]
I tried to keep the code as it is as much as I can. In some cases as you'll notice I had to do a lot of refactor

**Comment by MohamedMafaz** [comment]
Okay I'll Merge your PR. Thanks for your Contributions. I wish you could touch the peak of programming.

**Pull request merged**
